server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tailortrip_db?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 220211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        # JPA? ???? SQL? ?? ????? ??.
        show_sql: true
        # ??? ???? SQL? ????? ???? ?? ?????.
        format_sql: true

logging:
  level:
    org:
      springframework: info
      springframework.security: trace
    com:
      tailorTrip: debug


google:
  api:
    key:
