spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://3.34.25.202:3306/sys?useUnicode=true&serverTimezone=Asia/Seoul
    username: myo
    password: 220211
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        # JPA? ???? SQL? ?? ????? ??.
        show_sql: true
        # ??? ???? SQL? ????? ???? ?? ?????.
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id # 카카오에서는 id 속성을 사용하여 사용자 식별
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            user-name-attribute: sub  # 구글에서는 sub (구글 사용자 고유 ID)를 사용하여 사용자 식별
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response # 네이버에서는 response를 통해 사용자 정보를 가져옴
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me


        registration:
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: f0758a30cb8b661db1c0fc6cf81da576
            client-secret: 7WDgVcwpEEWapJalUp4PhiNwhji6Deqr
            client-authentication-method: client_secret_post  # new version orthography
            scope:
              - profile_nickname
              - account_email
          google:
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: 229264352456-nq7l48q0mkm2urqa0gvhvpb5teph96d1.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post  # new version orthography
            scope:
              - profile
              - email
          naver:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-id: Iudl2hoJisHTo2dC_aBE
            client-secret: 5AZ4CsVU4K
            client-authentication-method: client_secret_post  # new version orthography
            scope:
              - name
              - email



logging:
  level:
    org:
      springframework: info
      springframework.security: DEBUG
    com:
      tailorTrip: debug

batch:
  size: 50

google:
  api:
    key: AIzaSyD-jQLahI4UP9r5Zttz6yG7XJdhljzPjFw

weather:
  api:
    key: 58ac08cc8af3bbe943855ca0e973fff9

model:
  path: ${user.dir}/models/model.zip

kor:
  api:
    key: FoR6012UjGbYqAvG0XkZn3oM1uPihEZw5xSPmo9GmJfyBN2teJH5o0eKlkbFoK3sEs%2FAwLmbH1dgCCDsEsQ%2BEA%3D%3D

org:
  zerock:
    upload:
      path: C:\\upload
    #   JWT에서 사용할 비밀키
    jwt:
      secret: hello1234567890hello1234567890hello1234567890

