server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tailortrip_db?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 220211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        # JPA? ???? SQL? ?? ????? ??.
        show_sql: true
        # ??? ???? SQL? ????? ???? ?? ?????.
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: f0758a30cb8b661db1c0fc6cf81da576

            client-secret: 7WDgVcwpEEWapJalUp4PhiNwhji6Deqr
            client-authentication-method: client_secret_post  # new version orthography
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 229264352456-nq7l48q0mkm2urqa0gvhvpb5teph96d1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email


logging:
  level:
    org:
      springframework: info
      springframework.security: DEBUG
    com:
      tailorTrip: debug


google:
  api:
    key: AIzaSyD-jQLahI4UP9r5Zttz6yG7XJdhljzPjFw

weather:
  api:
    key: 58ac08cc8af3bbe943855ca0e973fff9

model:
  path: src/main/resources/model.zip

kor:
  api:
    key: FoR6012UjGbYqAvG0XkZn3oM1uPihEZw5xSPmo9GmJfyBN2teJH5o0eKlkbFoK3sEs%2FAwLmbH1dgCCDsEsQ%2BEA%3D%3D